version: '3.9'

services:
  app:
    container_name: php-login-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/public/:/var/www/html
    ports:
      - "8081:80" # Asegúrate de que el servidor web escuche en el puerto 80 en el contenedor
    depends_on:
      - db
    networks:
      - login-network
    restart: always

  db:
    image: postgres:15
    container_name: postgres-login-db
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: login_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - login-network
    restart: always

networks:
  login-network:
    driver: bridge

volumes:
  db-data:
