version: '3.9'

services:
  app:
    container_name: php-login-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/public:/var/www/html
      - ./app/node_modules:/var/www/html/node_modules # Cache de dependencias de Node.js
    ports:
      - "8081:80" # El servidor web escucha en el puerto 80 dentro del contenedor
    depends_on:
      - db
    networks:
      - login-network
    restart: always
    stdin_open: true # Necesario para comandos interactivos
    tty: true

  db:
    image: postgres:15
    container_name: postgres-login-db
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: login_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - login-network
    restart: always

networks:
  login-network:
    driver: bridge

volumes:
  db-data:
